S02 us03 modal product
WildCodeSchool-2024-09/JS-Paris-P2-GG pull request #9
Opened 2024-11-21 08:45 UTC by Claire-Cellier

2024-11-21 08:56 UTC, EmilieArnoux approved these changes
OK

2024-11-21 10:11 UTC, mickaellambert requested changes

2024-11-21 10:11 UTC, mickaellambert commented on src/App.tsx
> +			<Cards setSelectedProduct={setSelectedProduct} />
A renommer, "Cards" n'est pas un nom de composant hyper clair

2024-11-21 10:11 UTC, mickaellambert commented on src/App.tsx
> +			<Suggestions setSelectedProduct={setSelectedProduct} />
Peut être penser à créer un contexte pour le produit sélectionné

2024-11-21 10:11 UTC, mickaellambert commented on src/components/NavBar.tsx
> +							<Toggle />
Changer le nom du composant, peut être l'appeler "ToggleTheme"

2024-11-21 10:11 UTC, mickaellambert commented on src/components/ProductModal.tsx
> +				<button type="button" className="close" onClick={closeModal}>
`<button type="button" className="close" onClick={() => setSelectedProduct(null)}>`

2024-11-22 10:18 UTC, mickaellambert approved these changes

2024-11-22 10:18 UTC, merged